# A/B testing for creative directors
#
# This file contains the code for running an A/B test on a creative director.
# It is used to test the performance of a creative director against different providers.
#
# The A/B test is run by comparing the performance of a creative director against different providers.
# The performance is measured by the quality of the output generated by the creative director.
#
# The A/B test is run by comparing the performance of a creative director against different providers.
# The performance is measured by the quality of the output generated by the creative director.

# from __future__ import annotations

# import json
# from dataclasses import dataclass
# from pathlib import Path
# from typing import Iterable

# from pydantic import BaseModel, Field

# from studio.providers.llm.contracts import LLMProvider


# class BakeoffPrompt(BaseModel):
#     id: str = Field(min_length=1)
#     prompt: str = Field(min_length=1)


# @dataclass(frozen=True)
# class BakeoffResponse:
#     prompt_id: str
#     blind_label: str
#     provider: str
#     model: str
#     text: str


# def load_bakeoff_prompts(path: str | Path) -> list[BakeoffPrompt]:
#     prompts = [BakeoffPrompt.model_validate(item) for item in json.loads(Path(path).read_text())]
#     if len(prompts) != 10 or len({prompt.id for prompt in prompts}) != 10:
#         raise ValueError("creative bake-off must contain ten unique prompts")
#     return prompts


# def run_bakeoff(prompts: Iterable[BakeoffPrompt], providers: Iterable[LLMProvider]) -> list[BakeoffResponse]:
#     prompt_list = list(prompts)
#     provider_list = list(providers)
#     if len(prompt_list) != 10:
#         raise ValueError("creative bake-off must run exactly ten prompts")
#     responses = []
#     for provider_index, provider in enumerate(provider_list):
#         for prompt in prompt_list:
#             result = provider.generate(prompt.prompt)
#             responses.append(BakeoffResponse(prompt.id, chr(65 + provider_index), result.provider, result.model, result.text))
#     return responses
